spring.application.name=config-service
server.port=9999
#spring.cloud.config.server.git.uri=file:///C:/Users/hp/Desktop/bank-account-app/config-repo
spring.cloud.config.server.git.uri=https://github.com/SoufianeTrirach01/bank-account-config-repo



